# Project
group=com.github.glitchfiend
release_channel=beta

# Common
minecraft_version=1.21.9
common_runs_enabled=false
common_client_run_name=Common Client
common_server_run_name=Common Server

# Forge
forge_version=59.0.0

# NeoForge
neoforge_version=21.9.6-beta

# Fabric
fabric_version=0.133.14+1.21.9
fabric_loader_version=0.17.2

# Mod options
mod_name=TerraBlender
mod_author=Adubbz
mod_id=terrablender

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Dependencies
nightconfig_version=3.6.7
